import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import localFont from 'next/font/local';
import Footer from "@/components/Footer/Footer";




const openSans = Open_Sans({
  variable: '--font-open-sans', 
  subsets: ['latin'],
  // display: 'swap',
});

const podcastFont = localFont({
  src: "../../public/fonts/Podcast.ttf",
  display: 'swap',
  variable: '--font-podcast',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${podcastFont.variable} text-[#333333] font-open-sans overflow-x-hidden antialiased`}
      >
        <Navbar />
        <main className="mt-[12vh] md:mt-[15.74vh]">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
